version: '3.7'

services:

  IPDC_FRONTEND:
    container_name: IPDC_FRONTEND
    build: ./IPDC_FRONTEND
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 9004:3366
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start